OAS.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAS.Web.Controllers
{
    using filters;
    using Logic.Operations;
    public class AdminController : Controller
    {
        // GET: Admin
        [AdminAccessRequired]
        public ActionResult Index()
        {
            return View();
        }

        [AdminAccessRequired]
        public ActionResult reactivate(string username)
        {
            var usr = Get.SingleUser(username);

            usr.Reactivate();

            TempData["message"] = $"User '{usr.FullName}' has been reactivated!";

            return RedirectToAction("Index");
        }

        [AdminAccessRequired]
        public ActionResult Notify(string message, string userId)
        {
            var user = Get.SingleUser(int.Parse(userId));

            user.Notify(message);

            TempData["message"] = $"Notified {user.FirstName}!";

            return RedirectToAction("Index");
        }

        [AdminAccessRequired]
        public ActionResult deleteUser(int userId)
        {
            Delete.deleteUser(userId);

            TempData["message"] = "User has been deleted!";

            return RedirectToAction("Index");
        }

        [AdminAccessRequired]
        public ActionResult createUser(string Username, string Firstname, string Lastname, string Email, string Password, string admin = null)
        {
            if (Get.SingleUser(Username) != null)
            {
                TempData["badAlert"] = true;
                TempData["message"] = "Username is already taken!";

                return RedirectToAction("Index");
            }

            Create.NewUser(Username, Password, Firstname, Lastname, Email, admin == "on" ? true : false);

            TempData["message"] = $"User {Username} is created!";

            return RedirectToAction("Index");
        }

        public ActionResult Impersonate(int Id)
        {
            if (!Authentication.AuthenticatedAs.IsAdmin)
            {
                return RedirectToAction("IndexError", "Home");
            }
            else
            {
                Authentication.ImpersonatedFrom = Authentication.AuthenticatedAs;

                Authentication.AuthenticatedAs = Get.SingleUser(Id);

                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult unimpersonate()
        {
            if (!Authentication.ImpersonatedFrom.IsAdmin)
            {
                TempData["badAlert"] = true;
                TempData["message"] = "Nice try!";

                return RedirectToAction("Index", "Home");
            }
            Authentication.AuthenticatedAs = Authentication.ImpersonatedFrom;
            Authentication.ImpersonatedFrom = null;

            TempData["message"] = "Impersonation has ended. Welcome back " + Authentication.AuthenticatedAs.FirstName + "!";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult editUser(int userId, string Username, string Firstname, string Lastname, string Email, string Password, string Admin)
        {
            Update.updateUser(userId, new Logic.Types.User(Username, Password, Firstname, Lastname, Email, Admin == "on" ? true : false));

            TempData["message"] = "User has been updated!";

            return RedirectToAction("Index");
        }

        
    }
}

OAS.Web/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAS.Web.Controllers
{
    using Logic.Operations;
    using Logic.Types;

    public class MessageController : Controller
    {
        // GET: Message
        public ActionResult Index()
        {
            return View(Get.AllThreads().Where(thrds => thrds.Recipients.Any(usr => usr.Id == Authentication.AuthenticatedAs.Id)) as IEnumerable<Thread>);
            //this gets all threads where the current user has ANY relation to them as a recipient
        }

        [HttpPost]
        public ActionResult sendMessage(string threadId, string messageBody)
        {
            Get.SingleThread(int.Parse(threadId))
               .sendMessage(Authentication.AuthenticatedAs, messageBody);

            return null;
        }

        [HttpPost]
        public ActionResult createThread(string[] usernames)
        {
            var newusernames = new List<string>();

            usernames.ToList().ForEach(usernm =>
            {
                var tempName = usernm;

                tempName = tempName.Substring(tempName.IndexOf("(") + 1);

                tempName = tempName.Replace(")", "");

                newusernames.Add(tempName);
            });

            var users = Get.AllUsers().Where(x => x.IsActive && x.Id != 1);
            var filteredUsers = new List<User>();

            foreach(var user in users)
            {
                foreach(var username in newusernames)
                {
                    if (username == user.UserName)
                    {
                        filteredUsers.Add(Get.SingleUser(username));
                    }
                }
            }

            filteredUsers.Add(Authentication.AuthenticatedAs);

            Create.NewThread(filteredUsers);

            TempData["message"] = "New Thread created!";
            return RedirectToAction("Index");
        }
    }
}

OAS.Web/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAS.Web.Controllers
{
    using Logic.Operations;
    using Logic.Types;
    using System.Text.RegularExpressions;

    public class QuestionController : Controller
    {
        // GET: Question
        public ActionResult Ask()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addQuestion(string title, string body, string occupancy)
        {
            var newoccupancy = Regex.Replace(occupancy, @" \([0-9]* questions\)", "");

            if (!Get.AllOccupations().Any(x => x.Title == newoccupancy)) //if the user decided to edit the HTML before post back
            {
                TempData["badAlert"] = true;
                TempData["message"] = "Nice try!";
                return RedirectToAction("Ask");
            }
            else
            {
                Create.NewQuestion(title, body, Get.SingleOccupation(newoccupancy), Authentication.AuthenticatedAs);


                TempData["message"] = "Question created!";

                return RedirectToAction("Index", "Home");
            }
        }

        [Route("Question/{id}")]
        public ActionResult QuestionIndex(int id)
        {
            return View(Get.SingleQuestion(id));
        }

        public ActionResult secondQuestion(int questionId)
        {
            var question = Get.SingleQuestion(questionId);

            question.Second(Authentication.AuthenticatedAs);
            
            TempData["message"] = "Question seconded!";

            return RedirectToAction("QuestionIndex", new { id = question.Id });
        }

        public ActionResult unsecondQuestion(int questionId)
        {
            var question = Get.SingleQuestion(questionId);

            question.removeSecond(Authentication.AuthenticatedAs);

            
            TempData["message"] = "Question unseconded!";

            return RedirectToAction("QuestionIndex", new { id = question.Id });
        }

        public ActionResult editQuestion(int questionId)
        {
            var question = Get.SingleQuestion(questionId);

            if (question.Owner.UserName == Authentication.AuthenticatedAs.UserName || Authentication.AuthenticatedAs.IsAdmin) //? if the user decided to try and edit via URL
            {
                return View(question);
            }
            else
            {
                TempData["badAlert"] = true;
                TempData["message"] = "Nice try!";

                return RedirectToAction("QuestionIndex", new { id = questionId });
            }
        }

        public ActionResult updateQuestion(int questionId, string newtitle, string newbody, string newOccupancy)
        {
            var question = Get.SingleQuestion(questionId);

            question.Title = newtitle;
            question.Body = newbody;
            
            if (newOccupancy != question.AskedOccupation.Title)
            {
                question.AskedOccupation = Get.SingleOccupation(newOccupancy);
            }

            foreach (var ans in question.Answers)
            {
                foreach (var userOcc in ans.Owner.Occupations)
                {
                    if (userOcc.BaseOccupation.Id != question.AskedOccupation.Id)
                    {
                        Delete.deleteAnswer(ans.Id);
                    }
                }
            }
            question.update();

            
            TempData["message"] = "Successfully updated!";

            return RedirectToAction("QuestionIndex", new { id = questionId });
        }

        public ActionResult deleteQuestion(int questionId)
        {
            var question = Get.SingleQuestion(questionId);

            if (question.Owner.UserName == Authentication.AuthenticatedAs.UserName || Authentication.AuthenticatedAs.IsAdmin)
            {
                Delete.deleteQuestion(questionId);

                
                TempData["message"] = $"Question '{question.Title}' has been deleted!";

                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["badAlert"] = true;
                TempData["message"] = $"Nice try!";

                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult answerQuestion(int questionId, int ownerId, string answerBody)
        {
            if (ownerId == Authentication.AuthenticatedAs.Id && Authentication.AuthenticatedAs.Occupations.Any(x => x.BaseOccupation.Id == Get.SingleQuestion(questionId).AskedOccupation.Id))
            {
                Create.NewAnswer(ownerId, questionId, answerBody);
                Get.SingleQuestion(questionId).Owner.Notify($"New answer to {Get.SingleQuestion(questionId).Title}!", "/Question/QuestionIndex/" + questionId);
                TempData["message"] = "Question answered!";
                return RedirectToAction("QuestionIndex", new { id = questionId });
            }
            else
            {
                TempData["message"] = "Nice try!";
                return RedirectToAction("QuestionIndex", new { id = questionId });
            }
        }


        public ActionResult secondAnswer(int answerId)
        {
            var ans = Get.SingleAnswer(answerId);

            ans.Second(Authentication.AuthenticatedAs);

            TempData["message"] = "Answer seconded!";
            return RedirectToAction("QuestionIndex", new { id = ans.AnsweredQuestion.Id });

        }


        public ActionResult unsecondAnswer(int answerId)
        {
            var ans = Get.SingleAnswer(answerId);

            ans.removeSecond(Authentication.AuthenticatedAs);

            TempData["message"] = "Answer unseconded!";
            return RedirectToAction("QuestionIndex", new { id = ans.AnsweredQuestion.Id });

        }

        public ActionResult editAnswer(int answerId)
        {
            if (Get.SingleAnswer(answerId).Owner.Id == Authentication.AuthenticatedAs.Id)
                return View(Get.SingleAnswer(answerId));
            else
            {
                TempData["badAlert"] = true;
                TempData["message"] = "Nice try!";

                return RedirectToAction("QuestionIndex", new { id = Get.SingleAnswer(answerId).AnsweredQuestion.Id });
            }
        }

        public ActionResult deleteAnswer(int answerId)
        {
            var tempAnswerId = Get.SingleAnswer(answerId).AnsweredQuestion.Id; //? throws null exception due to answer having been deleted by the time I return

            Delete.deleteAnswer(answerId);

            TempData["message"] = "Answer deleted!";

            return RedirectToAction("QuestionIndex", new { id = tempAnswerId });
        }

        public ActionResult flagQuestion(int questionId, string reason)
        {
            Get.SingleQuestion(questionId).flag(Authentication.AuthenticatedAs, reason);

            TempData["message"] = "Question has been flagged! Reason: " + reason;

            return RedirectToAction("QuestionIndex", new { id = questionId });
        }

        public ActionResult unflagQuestion(int questionId)
        {
            Get.SingleQuestion(questionId).unflag(Authentication.AuthenticatedAs);

            TempData["message"] = "Question has been unflagged!";

            return RedirectToAction("QuestionIndex", new { id = questionId });
        }


    }
}

OAS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @{
#if DEBUG
        var debug = true;
#else
        var debug = false;
#endif
    }

    @if (!debug) //if this is live.
    {
        <base href="/oas/" />
    }
    @using Extensions;
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/sweetalert")
    @Scripts.Render("~/bundles/bootstrap-datepicker")
    @Scripts.Render("~/bundles/avsan")
    @Scripts.Render("~/bundles/Toastr")
    @Scripts.Render("~/bundles/game")
    @Scripts.Render("~/bundles/materialize")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar-fixed">
        @if (Authentication.IsAuthenticated)
        {
            <ul id="accountDropdown" class="dropdown-content">
                <li>@Html.ActionLink("Messages", "Index", "Message")</li>
                <li>@Html.ActionLink("My Account", "Index", "Account")</li>
                @if (Authentication.AuthenticatedAs.IsAdmin)
                {
                    <li>@Html.ActionLink("Admin panel", "Index", "Admin")</li>
                }
                <li>@Html.ActionLink("Log out", "logout", "Account")</li>
            </ul>

            <ul id="notificationDropdown" class="dropdown-content">
                @if (Authentication.AuthenticatedAs.NotificationsRecieved.Where(x => !x.Read).Count() < 1)
                {
                    <li><a href="#">No notifications here!</a></li>
                }

                @foreach (var notification in Authentication.AuthenticatedAs.NotificationsRecieved.Where(x => x.Read == false))
                {
                    <li class="notificationMenu" notId="@notification.Id"><a href="#">@notification.Body.Truncate(20)   @notification.DateSent.ToShortDateString()</a></li>
                }
            </ul>
        }
        <nav>
            <div class="nav-wrapper blue accent-2">
                <a href="@Url.Action("Index", "Home")" class="brand-logo">OAS</a>
                @if (Authentication.IsAuthenticated)
                {
                    <a href="#" data-activates="mobile-nav" class="button-collapse"><i class="fa fa-bars fa-fw"></i></a>
                }
                <ul class="right hide-on-med-and-down">
                    @if (Authentication.IsAuthenticated)
                    {
                        <li>
                            <a class="dropdown-button" href="#!" data-activates="notificationDropdown">
                                <i class="fa fa-bullhorn"></i>
                                @if (Authentication.AuthenticatedAs.NotificationsRecieved.Where(x => !x.Read).Count() > 0)
                                {
                                    <span id="notificationCount" class="new badge">@Authentication.AuthenticatedAs.NotificationsRecieved.Where(x => x.Read == false).Count() new</span>
                                }
                                else
                                {
                                    <span id="notificationCount" class="new badge">All caught up!</span>
                                }
                            </a>
                        </li>
                        <li>@Html.ActionLink("Ask Question", "Ask", "Question")</li>
                        <li><a class="dropdown-button" href="#!" data-activates="accountDropdown">My Account <img style="float: right; height: 56px !important" class="circle hide-on-med-and-down" src="@(Authentication.AuthenticatedAs.GravatarURL ?? "/Content/defaultGravatar.jpg")" /></a></li>
                    }
                </ul>
                <ul class="side-nav" id="mobile-nav">
                    @if (Authentication.IsAuthenticated)
                    {
                        <li><a href="@Url.Action("Index", "Account")"><img style="height: 95%" class="circle" src="@(Authentication.AuthenticatedAs.GravatarURL ?? "/Content/defaultGravatar.jpg")" /> @Authentication.AuthenticatedAs.UserName</a></li>
                    }
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        @if (Authentication.isImpersonated)
        {
            <div class="alert alert-warning">
                You are impersonating @Authentication.AuthenticatedAs.FullName. Please be mature! Click @Html.ActionLink("here", "unimpersonate", "Admin") to stop Impersonating @Authentication.AuthenticatedAs.FullName
            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - OAS</p>
        </footer>
    </div>

    <script>
        $(document).ready(function () {
            $('div[style="opacity: 0.9; z-index: 2147483647; position: fixed; left: 0px; bottom: 0px; height: 65px; right: 0px; display: block; width: 100%; background-color: #202020; margin: 0px; padding: 0px;"]').remove();
            $('div[style="position: fixed; z-index: 2147483647; left: 0px; bottom: 0px; height: 65px; right: 0px; display: block; width: 100%; background-color: transparent; margin: 0px; padding: 0px;"]').remove();
            //removes the annoying injected footer on live

            Materialize.updateTextFields();
            $(".button-collapse").sideNav();
            $('select').material_select();
            $('.modal-trigger').leanModal();
            $(".dropdown-button").dropdown();
        })

        $('#notificationDropdown li.notificationMenu').on('click', function () {
            var elem = $(this);

            $.post("@Url.Action("markNotificationRead", "Account")",
                {
                    notificationId: $(elem).attr('notId')
                },
                function () {
                    var newNotificationCount = $(elem).parent().children().length - 1;

                    $(elem).remove();
                    if (newNotificationCount === 0) {
                        $('#notificationCount').text('All caught up!');
                        $(elem).parent().append('<li><a href="#">No notifications here!</a></li>');
                    }
                    else {
                        $('#notificationCount').text(newNotificationCount.toString() + ' new');
                    }
                }
            );
        });

        $(function () {
            $('.avsan').each(function () {
                var elem = $(this);
                var innerText = $(elem).text();

                var replacetext = innerText.match(/~~ avsan: (.*?)~~/g);

                replacetext.forEach(function (str) {
                    var job = str.replace('~~ avsan: ', '').replace(' ~~', '');
                    var end = AvsAn.query(job + ' ').article;

                    var final = str.replace(str, end) + ' ' + job;
                    $(elem).text($(elem).text().replace(str, final));
                })
            })

            var frogger = new Konami(function () {
                $('#konamiModal').openModal({
                    dismissable: false,
                    ready: function () { start_game() }, 
                    complete: function () { stop_game(); }
                });
            })
        })
    </script>

    @if (TempData["message"] != null)
    {
        if ((bool?)TempData["badAlert"] == true) //comes out as an object, needs cast
        {
            <script>
                toastr.options.preventDuplicates = true;
                toastr.options.newestOnTop = true;

                toastr.error("@TempData["message"]");
            </script>
        }
        else
        {
            <script>
                toastr.options.preventDuplicates = true;
                toastr.options.newestOnTop = true;

                toastr.info("@TempData["message"]");
            </script>
        }
    }

    @if (Authentication.IsAuthenticated)
    {
        <script>
        $(document).ready(function () {
            setInterval(function () {
                $.get('/Account/GetUnreadNotification', function (data) {
                    var notifications = data.split(';;');
                    notifications.forEach(function (notification) {
                        var id = notification.split("~;")[0];
                        var body = notification.split("~;")[1];
                        var datesent = notification.split("~;")[2];

                        var exists;
                        $('#notificationDropdown').children().each(function () {
                            if ($(this).attr('notId') === id || body == undefined) {
                                exists = true;
                            }
                        })

                        if (exists !== true) {
                            $('#notificationDropdown').append('<li class="notificationMenu" notId="' + id + '"><a href="#">' + body + '   ' + datesent + '</a></li>');
                            var currentCount = parseInt($('#notificationCount').text().replace(' new', ''));

                            var newCount = currentCount + 1;

                            $('#notificationCount').text(newCount.toString() + ' new');
                        }
                    })
                });
            }, 2000)
        })
        </script>
    }

    <script>
        console.log('       .--.  .-\'\'\'-.  .--.');
        console.log('      /."".v\'.-. .-.`v.""\\\\');
        console.log('      ||  / / O| | O\\ \\  ||');
        console.log('      \\\\_/| \\__| |__/  \\_//');
        console.log('       `-\'\\  .-n-n-.  /`-\'');
        console.log('        _.-\\/       \\/-._');
        console.log('      .\'   (\\`.___.\'/)   `.');
        console.log('     /      \\`.___.\'/      `.');
        console.log('    /        `.___.\'         \\');
        console.log('    |     |             \\     \\');
        console.log('    |     |   .      .  |\\     \\');
        console.log('    |     |             | \\     \\');
        console.log('     \\     \\            |  \\     \\');
        console.log('      \\     \\           |.\' `.    \\');
        console.log('       `.    \\         .\'     `.   \\');
        console.log('  _.._   `.   `-. ___ /        /`.  `.');
        console.log('.\'    `-._ `.    `.__)       .\'  /    `.');
        console.log('|         `-.\\     \\/      .\'   / /\\  )|\\.');
        console.log(' \\          _/ / /|/     .\'    (_/ / / | \\)');
        console.log('  `._      (__/_/-/   ..\'         (_/| |\\_)');
        console.log('     ``--._____.-(     `.            `-\'');
        console.log('                  `--.   `.');
        console.log('                    (_/\\ \\\\\\');
        console.log('                       /_///');
    </script>

    <div id="konamiModal" class="modal hide-on-med-and-down" style="height: 760px; width: 600px;">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-content">
                    <h4>Ribbit</h4>
                    <div id="game_div" class="center">
                        <canvas width="400" height="550" id="game"></canvas>
                    </div>
                </div>
                <div class="modal-footer">
                    <a id="konamiModalClose" href="#!" class="modal-action modal-close waves-effect blue accent-2 btn">Close</a>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</body>
</html>